# Change these first
owner: pmjustin # Your GitHub organization or username, where this repository lives
repo: pmuptime # The name of this repository

sites:
  - name: Personable Media
    url: https://personablemedia.com/
  - name: Estate Planning Lead Pros
    url: https://estateplanningleadpros.com/
  - name: Rost Motors
    url: https://rostmotor.com/
  - name: Michael Bailey Law Office
    url: https://michaelbaileylawllc.com/
  - name: Saeed & Little Law
    url: https://willandtrustindy.com/
  - name: Arvada Tri
    url: https://arvadatri.com/

status-website:
    theme: dark # status-website theme
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
    #cname: demo.upptime.js.org
    name: Personable Media
    baseUrl: /pmuptime
    logoUrl: https://personablemedia.com/wp-content/uploads/2020/10/pm_websitepartner_300px.png # Personable Media logo
    name: Personable Media Client Site Monitoring
    introTitle: "**PMUPTIME** is the Personable Meida Client Site Monitoring service powered entirely by GitHub."
    introMessage: "Below is the Client Site status reports"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/pmjustin/pmuptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
