# Change these first
owner: pmjustin # Your GitHub organization or username, where this repository lives
repo: pmuptime # The name of this repository

sites:
  - name: Personable Media # Added 1/11/2022
    url: https://personablemedia.com/
  - name: Estate Planning Lead Pros # Added 1/11/2022
    url: https://estateplanningleadpros.com/
  - name: Rost Motors # Added 1/11/2022
    url: https://rostmotor.com/
  - name: Michael Bailey Law Office # Added 1/12/2022
    url: https://michaelbaileylawllc.com/
  - name: Saeed & Little Law # Added 1/12/2022
    url: https://willandtrustindy.com/
  - name: Arvada Tri # Added 1/12/2022
    url: https://arvadatri.com/
  - name: Fast Lane Swimming # Added 1/12/2022
    url: https://fastlaneswimming-colorado.com/
  - name: Fish of Westminister # Added 1/12/2022
    url: https://fishofwestminster.org/
  - name: Garramones Pizza # Added 1/12/2022
    url: https://garramonespizza.com/
  - name: Glamorous Or Not # Added 1/12/2022
    url: https://glamorousornot.com/
  - name: Higher Mind Healing # Added 1/12/2022
    url: https://highermindhealing.net/
  #- name: Mindy Arbuckle # Added 1/12/2022 - Cancelled Services
    #url: https://mindyarbuckle.com/
  - name: Ulonda Faye # Added 1/12/2022
    url: https://ulondafaye.com/

status-website:
    theme: night # status-website theme
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
    cname: monitor.personableapps.com
    #baseUrl: /pmuptime
    logoUrl: https://personablemedia.com/wp-content/uploads/2020/10/pm_websitepartner_300px.png # Personable Media logo
    name: Personable Media Client Site Monitoring
    introTitle: "This is the **Personable Meida Client Site Monitoring** service."
    introMessage: "Below is the Client Site status reports"
    navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
